export default  {
"login": "nohahassan64",
"id": 69641077,
"node_id": "MDQ6VXNlcjY5NjQxMDc3",
"avatar_url": "https://avatars.githubusercontent.com/u/69641077?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/nohahassan64",
"html_url": "https://github.com/nohahassan64",
"followers_url": "https://api.github.com/users/nohahassan64/followers",
"following_url": "https://api.github.com/users/nohahassan64/following{/other_user}",
"gists_url": "https://api.github.com/users/nohahassan64/gists{/gist_id}",
"starred_url": "https://api.github.com/users/nohahassan64/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/nohahassan64/subscriptions",
"organizations_url": "https://api.github.com/users/nohahassan64/orgs",
"repos_url": "https://api.github.com/users/nohahassan64/repos",
"events_url": "https://api.github.com/users/nohahassan64/events{/privacy}",
"received_events_url": "https://api.github.com/users/nohahassan64/received_events",
"type": "User",
"site_admin": false,
"name": "Noha Hassan",
"company": null,
"blog": "",
"location": "Kuwait",
"email": null,
"hireable": null,
"bio": "Iam Noha Hassan. I learn web design .",
"twitter_username": null,
"public_repos": 18,
"public_gists": 0,
"followers": 0,
"following": 2,
"created_at": "2020-08-13T15:32:28Z",
"updated_at": "2021-05-02T21:51:58Z"
};